[workspace]
authors = ["Coral Quering <ciq0001@uah.edu>"]
channels = ["conda-forge"]
name = "hw1"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=25.3,<26"
ipykernel = ">=7.1.0,<8"
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
xarray = ">=2025.12.0,<2026"
cartopy = ">=0.25.0,<0.26"
