[workspace]
authors = ["Coral Quering <ciq0001@uah.edu>"]
channels = ["conda-forge"]
name = "hw1"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=26.0,<27"
ipykernel = ">=7.1.0,<8"
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
xarray = ">=2025.12.0,<2026"
cartopy = ">=0.25.0,<0.26"
netcdf4 = ">=1.7.4,<2"
h5netcdf = ">=1.8.1,<2"
folium = ">=0.20.0,<0.21"
