[workspace]
authors = ["Coral Quering <ciq0001@uah.edu>"]
channels = ["conda-forge"]
name = "ce1"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=26.0.1,<27"
ipykernel = ">=7.1.0,<8"
pandas = ">=3.0.0,<4"
geopandas = ">=1.1.2,<2"
folium = ">=0.20.0,<0.21"
